const currencyForm = document.getElementById("currency_form");
const resultDiv = document.getElementById("result");

// Function to get the exchange rate
async function getExchangeRate(fromCurrency, toCurrency) {
    await new Promise(resolve => setTimeout(resolve, 100));
    const exchangeRate = {
            "Afghan Afghani": {
                "Albanian Lek": 1.346,
                "Armenian Dram": 0.7325,
                "Algerian Dinar": 1.9423,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "Albanian Lek": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "Indian Rupee": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "United States Dollar": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "Angolan Kwanza ": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "Algerian Dinar": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
        "Indian Rupee": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
            "United States Dollar": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
        "" : {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "United States Dollar": 23.2,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            },
        "United States Dollar": {
                "Afghan Afghani": 1.36,
                "Armenian Dram": 0.75,
                "Algerian Dinar": 1.94,
                "Angolan Kwanza": 12.04,
                "Argentine Peso": 5.26,
                "Aruban Florin": 0.026,
                "Australian Dollar": 0.022,
                "Azerbaijani Manat": 0.025,
                "Bahamian Dollar": 0.014,
                "Bahraini Dinar": 0.0055,
                "Bajan dollar": 0.029,
                "Bangladeshi Taka": 1.59,
                "Belarusian Ruble": 0.048,
                "Belize Dollar": 0.029,
                "Bermuda Dollar": 0.014,
                "Bhutanese Ngultrum": 1.20,
                "Bolivian boliviano": 0.100,
                "Bosnia-Herzegovina Convertible Marka": 0.026,
                "Bostwanan Pula": 0.20,
                "Brazilian Real": 0.071,
                "Brunei Dollar": 0.019,
                "Bulgarian Lev": 0.026,
                "Burundian Franc": 41.07,
                "CFP Franc": 1.60,
                "Combodian riel": 59.41,
                "Canadian Dollar": 0.020,
                "Cape Verdean Escudo": 1.48,
                "Cayman Islands Dollar": 0.012,
                "Central African CFA franc": 8.79,
                "Chilean Peso": 12.92,
                "Chilean Unit of Account (UF)": 0.00034,
                "Chinese Yuan": 0.10,
                "Chinese Yuan (offshore)": 0.10,
                "Colombian Peso": 57.82,
                "Comorian Franc": 6.59,
                "Congolese Franc": 37.80,
                "Costa Rican Colon": 7.62,
                "Cuban Peso": 0.35,
                "Czech Koruna": 0.33,
                "Danish Krone": 0.100,
                "Djiboutian Franc": 2.57,
                "Dominican Peso": 0.82,
                "East Caribbean Dolla": 0.039,
                "Egyptian Pound": 0.45,
                "Ethiopian Birr": 0.81,
                "Euro": 0.013,
                "Fijian Dollar": 0.032,
                "Gambian Dalasi": 0.97,
                "Georgian Lari": 0.039,
                "Ghanaian Cedi": 0.17,
                "Guatemalan Quetzal": 0.11,
                "Guinean Franc": 12.07,
                "Guyanaese Dollar": 3.02,
                "Haitian Gourde": 0.122,
                "Honduran Lempira": 0.36,
                "Hong Kong Dollar": 0.11,
                "Hungarian Forint": 0.212,
                "Icelandic Krona": 34.43,
                "Indian Rupee": 1.21,
                "Indonesian Rupiah": 23.2,
                "Iranian Rial": 2.2,
                "Iraqi Dinar": 9.1,
                "Israeli New Shekel": 0.111,
                "Jamaican Dollar": 2.21,
                "Japanese Yen": 4.8,
                "Jordanian Dinar": 76.2,
                "Kazakhstani Tenge": 90.1,
                "Kenyan Shilling": 9.1,
                "Kuwaiti Dinar": 50.3,
                "Kygystani Som": 89,
                "Laotian Kip": 45.4,
                "Lebanese pound": 65.4,
                "Lesotho Loti": 43.2,
                "Liberian Dolla": 78.1,
                "Libyan Dinar": 34.2,
                "Macanese Pataca": 98.1,
                "Macedonian Denar": 12.9,
                "Malagasy Ariary": 23.1,
                "Malawian Kwacha": 56,
                "Malaysian Ringgit": 0.011,
                "Maldivian Rufiyaa": 12.9,
                "Mauritian Rupee": 23.1,
                "Mexican Peso": 0.044,
                "Moldovan Leu": 0.098,
                "Moroccan Dirham": 0.082,
                "Mozambican metical": 0.023,
                "Myanmar Kyat": 0.034,
                "Namibian Dollar": 0.78,
                "Nepalese Rupee": 0.67,
                "Netherlands Antillean Guilder": 5.5,
                "New Taiwan dollar": 9.12,
                "New Zealand Dollar": 0.98,
                "Nicaraguan Cordoba": 0.92,
                "Nigerian Naira": 3.3,
                "Norwegian Krone": 23.1,
                "Omani Rial": 12.1,
                "Pakistani Rupee": 12.1,
                "Panamanian Balboa": 12.6,
                "Papua New Guinean Kina": 1.1,
                "Paraguayan Guarani": 23.2,
                "Philippine peso": 3.43,
                "Polish Zloty": 12.9,
                "Pound sterling": 0.88,
                "Qatari Riyal": 12.1,
                "Romanian Leu": 0.21,
                "Russian Ruble": 23.2,
                "Rwandan Franc": 34.3,
                "Salvadoran Colon": 12.11,
                "Saudi Riyal": 0.03,
                "Serbian Dinar": 0.98,
                "Seychellois Rupee": 0.34,
                "Singapore Dollar": 34.3,
                "Sol": 23.98,
                "Solomon Islands Dollar": 19.98,
                "Somali Shilling": 0.32,
                "South African Rand": 78.9,
                "South Korean won": 0.56,
                "Sri Lankan Rupee": 0.97,
                "Sudanese pound": 0.78,
                "Suriname Dollar": 3.33,
                "Swazi Lilangeni": 0.087,
                "Swedish Krona": 9.78,
                "Swiss Franc": 0.62,
                "Tajikistani Somoni": 0.78,
                "Thai Baht": 34.5,
                "Tongan Pa'anga": 0.912,
                "Trinidad & Tobago Dollar": 45.4,
                "Tunisian Dinar": 45.43,
                "Turkish Lira": 65.3,
                "Turkmenistani Manat": 45.3,
                "Ugandan Shilling": 23.2,
                "Ukrainian hryvnia": 36.6,
                "United Arab Emirates Dirham": 98.1,
                "Uruguayan peso": 34.3,
                "Uzbekistani Som": 7.9,
                "Vietnamese dong": 98.8,
                "West African CFA franc": 24.2,
                "Yemeni Rial": 4.4,
                "Zambian Kwacha": 5.5
            }
        }
    const rate = exchangeRate[fromCurrency] && exchangeRate[fromCurrency][toCurrency];
    if (!rate) {
        console.error(`Exchange rate not available for ${fromCurrency} to ${toCurrency}`);
        return null;
    }
    return rate;
}

currencyForm.addEventListener("submit", async function (e) {
    e.preventDefault();

    const fromCurrency = document.getElementById("gon1").value;
    const toCurrency = document.getElementById("gon2").value;
    const amount = parseFloat(document.getElementById("forcing").value);

    // Call the getExchangeRate function
    const exchangeRate = await getExchangeRate(fromCurrency, toCurrency);

    if (exchangeRate !== null) {
        const convertedAmount = (amount * exchangeRate).toFixed(2);
        resultDiv.innerHTML = `${amount} ${fromCurrency} is equal to ${convertedAmount} ${toCurrency}`;
    } else {
        resultDiv.innerHTML = "Unable to retrieve exchange rate or invalid currency pair.";
    }
})